version: '3'

services:
    management-partner:
        build: .
        ports:
            - 32768:80

        depends_on:
            - mongo
        links:
            - mongo

    mongo:
        container_name: mongo
        image: mongo:3.5
        restart: always
        ports:
            - 27017:27017